# Generated by Django 4.0.5 on 2022-08-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_player_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
    ]
