# Generated by Django 4.0.5 on 2022-08-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_player_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
    ]
