# Generated by Django 4.0.5 on 2022-08-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
