# Generated by Django 4.0.5 on 2022-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default='2022-08-04', verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=models.TextField(verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='news',
            name='header',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
